---
#
# Ansible managed
#
repository:
  description: The purpose of this role is to install and configure php_fpm on your system.
  homepage: https://robertdebock.nl/
  topics: phpfpm, fpm, ansible, molecule, tox, playbook
